# Build stage
FROM node:20 AS builder
WORKDIR /app
# Copy all files to ensure public and src are available
COPY . .
# Add environment variables during build
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID
RUN npm ci
RUN npm run build

# Production stage
FROM node:20
WORKDIR /app
# Install serve globally
RUN npm install -g serve
# Copy the dist folder from the builder stage
COPY --from=builder /app/dist ./dist
# Set the port environment variable
ENV PORT=8080
# Expose the port
EXPOSE $PORT
# Run serve to serve the dist folder
CMD ["sh", "-c", "serve -s dist -l $PORT"]
