sonar.projectKey=mahdaf_shopping-list
sonar.organization=mahdaf

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=shopping-list
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Branch configuration for analysis
sonar.branch.name = staging
sonar.branch.target = main

# Folder file test 
sonar.tests=src

# Path to coverage report (LCOV)
sonar.javascript.lcov.reportPaths=./coverage/lcov.info